kind: ENC[AES256_GCM,data:DMxbMCjm,iv:KTky7nAZX8Ggko52+oQh4c9zoWgPsQZJIVMzCrnFDJA=,tag:Y5utG16Sd6pHunP4cB/7Hw==,type:str]
ansible_user: ENC[AES256_GCM,data:AVzPOWs=,iv:N60WQcm6PunxqkzhYOZU11EBnue/VonBymYIEX7lAjI=,tag:VnTAzZLiJoHGAVk4mD0WGw==,type:str]
ansible_become_pass: ENC[AES256_GCM,data:1elIJ5O1byTTMPfpjH64QOwuLFQ=,iv:B8OJ2MTAOZYrvlHqzT9VYGe7fzj+KdCN0SIj2yK8rdY=,tag:MXSvK2DBxsOC0bFm5ZjOWw==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1sens6q7vmpr3339ffmgff686r5gkmzmmg9wkns6f9ltae7lked7swvq6aw
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBucWpLZllBSHA0SUx4MnJt
            WDFscUZ4WFlHNjMxRFpiRmIxUFgxcEZqVmdJCmsyWGhwckFncEZsK1dEUGk4bVVR
            dmtlelJpLzFhbm16SHVaQndvbExVbUEKLS0tIEVYdG5TSWFQdkNhK3ZFMXZIUEtk
            dHcrMkRVMkhza1U2ekpWMEM5N21uRDgKaRNhY7UWfNnzFhVGcXBmZGBQLi3oOAiR
            RzpEHLACQ+CZTq0So7qbN+XPA1MmUOsAb5RNAMk696kZ4tlLpAaUWg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2023-04-29T05:15:30Z"
    mac: ENC[AES256_GCM,data:20BDTGG/i4XkjrwOX97nt4VeAv1Grfpqw+F9jU8nSt6NkTI3O4hW2P/+6co+iVyUMPISDSUKwa2RYYQjRtk/EBasI4r9vkK5qU2Skdyuc7c9LxpG7t9tYlPtNEVO2z+Myh255sGW0bjIGiMCrDZ4ahYO+L+C93v8LgQT4C5TOvU=,iv:v5wXyi8OXShRt7zqxxXMyCPqnPYT+KuIAM5lPwIr1WA=,tag:8h+RbaWzqSYzrfSZRQ8uYw==,type:str]
    pgp: []
    unencrypted_suffix: _unencrypted
    version: 3.7.3
