---
apiVersion: kustomize.toolkit.fluxcd.io/v1beta2
kind: Kustomization
metadata:
  name: cluster-apps-vpn
  namespace: flux-system
spec:
  path: ./kubernetes/apps/media/vpn/app
  prune: true
  sourceRef:
    kind: GitRepository
    name: home-kubernetes
