apiVersion: v1
kind: Secret
metadata:
    name: weave-gitops-secret
    namespace: flux-system
type: Opaque
stringData:
    adminPassword: ENC[AES256_GCM,data:x0t1IWkS+XVUBj4+Fn5V9gKNHiCPQ6lyBhylKXslEf2gYbr+K3ghjyJS4PkUKY6epTSBFHwFXcpfve5U,iv:e0RK7h0gZT0SDDL+O1Z/6pUeFqCyxSfilhNgJ65X9M4=,tag:CgfxrMKtPq29zrbCWWRGFQ==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1sens6q7vmpr3339ffmgff686r5gkmzmmg9wkns6f9ltae7lked7swvq6aw
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBLNTlqMG1HeHI5U3VaeVJH
            ZnVJNGVRaEdLdEhhSEw4RUdrTEduaVVCR1N3Ck5ib0lTQWphckJaenB3Y2VXV1ZF
            YVJTUE9PWHVFOWVMM3JpeVhESi9vS1UKLS0tIFl4ZHR6N21ZTjJCc1BuaVdnZjly
            K2cvZkZwTWkvS1phT0ErYUFIamhWRXMK2f3nDNUjaIpkm5hRxu1aOoc77gJCu4nP
            ++ykOk6hvQ9gvnoNnX1Sd0LS2JnxH9qSvE2TaYlWoMVS4BjOD/Pibg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2023-04-23T20:06:49Z"
    mac: ENC[AES256_GCM,data:CayFqTslhNJi3DBoBDdiSFUD7hYt+r04laRqkHvtL1APykgXiwTMJGGDn1ZxY+hA3PpY3vlwOuzyewsxqJxnUZ6eATqzQEwT+Lpv3RJjNzFbfsiQoBTx0nHwaKljh4BoQzLVTjt32yN8eu1mhYQQ/dMxsT+wprIQgSx3qNjpdrE=,iv:bsaZUagiVNhHjpRlv7ciH5XBTG9+aR+x/kWLl032dIk=,tag:T1ygMmHAo8cmbuKqlkFHkw==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.7.3
