---
apiVersion: v1
kind: ConfigMap
metadata:
  name: cluster-settings
  namespace: flux-system
data:
  TIMEZONE: "Europe/Paris"
  KUBE_VIP_ADDR: "192.168.1.80"
  METALLB_LB_RANGE: "192.168.1.60-192.168.1.70"
  METALLB_K8S_GATEWAY_ADDR: "192.168.1.69"
  METALLB_INGRESS_ADDR: "192.168.1.70"
